version: "3.9"

services:
  mongodb:
    image: "mongo:latest"
    volumes:
      - ./db:/data/db
    ports:
      - 2717:27017

  maas_backend:
    image: ${IMAGE:-maas-backend:local}
    build: ./
    restart: unless-stopped
    environment:
      - PORT=8080
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    command:
      [
        "npm",
        "start"
      ]

